from tkinter import *


def click(event):
  global scvalue
  text=event.widget.cget("text")
  if text == "=":
    if scvalue.get().isdigit():
      value = int(scvalue.get())
    else:
      try:
        value = eval(screen.get())
      except Exception as e:
        print(e)
        value = "Error"
        
    scvalue.set(value)
    screen.update()
  elif text == "C":
    scvalue.set("")
    screen.update()
  elif text == "DEL":
    
    scvalue.set(scvalue.get()[:-1])
    scvalue.update()
   
    
  else:
    scvalue.set(scvalue.get() + text)
    screen.update()
    
root = Tk()
root.geometry("225x275")
root.minsize(225,275)
root.maxsize(225,275)
root.title("Calculator")
root.config(bg="#F5F5F5")
scvalue = StringVar()
scvalue.set("")
screen = Entry(root, textvar = scvalue,font = "lucida 20 bold",relief=SOLID,bg="#FFFFFF",fg="#000000")
screen.pack(ipadx=4, padx=6, pady=6, fill=X)

f1=Frame(root,bg="#000000")
f1.pack(pady=4,padx=4)
b1=Button(f1,text="C",font= "Arial 12 bold", width=2,height=1,bg='#FF4433',relief=SOLID)
b1.grid(row=2, column=1)
b1.bind("<Button-1>",click)
b2=Button(f1,text="DEL",font= "Arial 12 bold",width=2,height=1,bg="#DFFF00",relief=SOLID)
b2.grid(row=2, column=2)
b2.bind("<Button-1>",click)
b3=Button(f1,text="%",font= "Arial 12 bold",width=2,height=1,relief=SOLID,bg='#FFAC1C',fg="black")
b3.grid(row=2, column=3)
b3.bind("<Button-1>",click)
b4=Button(f1,text="=",font= "Arial 12 bold",width=2,height=1,relief=SOLID,bg='#FFAC1C')
b4.grid(row=2, column=4)
b4.bind("<Button-1>",click)
f2=Frame(root,bg="#000000")
f2.pack(pady=4,padx=4)
b1=Button(f2,text="7",font= "Arial 12 bold",width=2,height=1,relief=SOLID)
b1.grid(row=3, column=1)
b1.bind("<Button-1>",click)
b2=Button(f2,text="8",font= "Arial 12 bold",width=2,height=1,relief=SOLID)
b2.grid(row=3, column=2)
b2.bind("<Button-1>",click)
b3=Button(f2,text="9",font= "Arial 12 bold",width=2,height=1,relief=SOLID)
b3.grid(row=3, column=3)
b3.bind("<Button-1>",click)
b4=Button(f2,text="+",font= "Arial 12 bold",width=2,height=1,relief=SOLID,bg='#FFAC1C')
b4.grid(row=3, column=4)
b4.bind("<Button-1>",click)
f3=Frame(root,bg="#000000")
f3.pack(pady=2,padx=2)
b1=Button(f3,text="4",font= "Arial 12 bold", width=2,height=1,relief=SOLID)
b1.grid(row=4, column=1)
b1.bind("<Button-1>",click)
b2=Button(f3,text="5",font= "Arial 12 bold",width=2,height=1,relief=SOLID)
b2.grid(row=4, column=2)
b2.bind("<Button-1>",click)
b3=Button(f3,text="6",font= "Arial 12 bold",width=2,height=1,relief=SOLID)
b3.grid(row=4, column=3)
b3.bind("<Button-1>",click)
b4=Button(f3,text="-",font= "Arial 12 bold",width=2,height=1,relief=SOLID,bg='#FFAC1C')
b4.grid(row=4, column=4)
b4.bind("<Button-1>",click)
f4=Frame(root,bg="#000000")
f4.pack(pady=4,padx=4)
b1=Button(f4,text="1",font= "Arial 12 bold", width=2,height=1,relief=SOLID)
b1.grid(row=4, column=1)
b1.bind("<Button-1>",click)
b2=Button(f4,text="2",font= "Arial 12 bold",width=2,height=1,relief=SOLID)
b2.grid(row=4, column=2)
b2.bind("<Button-1>",click)
b3=Button(f4,text="3",font= "Arial 12 bold",width=2,height=1,relief=SOLID)
b3.grid(row=4, column=3)
b3.bind("<Button-1>",click)
b4=Button(f4,text="*",font= "Arial 12 bold",width=2,height=1,relief=SOLID,bg='#FFAC1C')
b4.grid(row=4, column=4)
b4.bind("<Button-1>",click)
f5=Frame(root,bg="#000000")
f5.pack(pady=4,padx=4)
b1=Button(f5,text=".",font= "Arial 12 bold", width=2,height=1,relief=SOLID)
b1.grid(row=5, column=1)
b1.bind("<Button-1>",click)
b2=Button(f5,text="0",font= "Arial 12 bold",width=2,height=1,relief=SOLID)
b2.grid(row=5, column=2)
b2.bind("<Button-1>",click)
b3=Button(f5,text="00",font= "Arial 12 bold",width=2,height=1,relief=SOLID)
b3.grid(row=5, column=3)
b3.bind("<Button-1>",click)
b4=Button(f5,text="/",font= "Arial 12 bold",width=2,height=1,relief=SOLID,bg='#FFAC1C')
b4.grid(row=5, column=4)
b4.bind("<Button-1>",click)
root.mainloop()